### ISSUE TITLE
Smurf not working correctly on rails 2.3.10

### ISSUE THREAD

**Issue by mcollina** [thumblemonks/smurf#11]
The latest version that support rails 2.3.x is v1.0.4, but in that version only the javascripts inside public/javascripts are minified. 
After digging up a little in the code, I've found that this should be solved in the latest v1.0.5 which works only on rails 3. 

Is it too hard to support both rails2.3.x and rails3 on the same branch?

**Comment by peppyheppy** [comment]
The gem its self works on both 2.3.x and 3, but it depended on rails 3 for tests within the Gemfile. I just moved the rails dependency into the test environment in the Gemfile so you are no longer required to have rails 3 installed to use the gem with 2.3.x.

Because the tests use rails 3 there is no guarantee that older versions of rails will work, but they probably will anyway.

Good luck!

**Comment by mcollina** [comment]
That's fine :).

It's working smoothly on our rails 2.3.10 application, no issue at all.

Matteo
